### ISSUE TITLE
Error when trying to access non exist poll.

### ISSUE THREAD

**Issue by ReggieReo** [Sosokker/ku-polls#56]
Application shows error "Not Found" when trying to access non exist poll when visitor is logged in, but when visitor is not logged in Application redirect visitor to log in page normally.

<a href="https://ibb.co/ZBMNzVm"><img src="https://i.ibb.co/D9RLftp/Screenshot-2566-09-25-at-13-42-17.png" alt="Screenshot-2566-09-25-at-13-42-17" border="0" /></a>

**Comment by Sosokker** [comment]
It looks like the problem is on the get method of the DetailView class, so I override it.
- When User try to access invalid poll -> Django get Return Http404 -> Redirect user to Index

Thank you!
